### PR TITLE
LivepeerTV: change application url

### PR DESCRIPTION
**Pull request by pblvrt**
Change URL of livepeerTV proxy in next.conf.js

### CODE REVIEW

**Review by rickstaa — APPROVED** [review]
Looks good to me.

**Comment by pblvrt** [comment]
hello guys, can we merge this plz :) @iameli @adamsimms

**Comment by iameli** [comment]
@pblvrt Looks like that new link isn't public, that intended?

**Comment by pblvrt** [comment]
@iameli my bad, copied the wrong link from vercel, just fixed it

**Comment by iameli** [comment]
@pblvrt Can you do one more for `https://livepeer.org/livepeer.tv` to redirect to that domain? That's where `https://livepeer.tv` redirects to, so I think that'll get everything to the right place.

**Comment by iameli** [comment]
ty, merging when CI passes

**Comment by pblvrt** [comment]
ty

**Review by adamsoffer — COMMENTED** [review]
🚢

**Pull request merged**
